import type { Metadata } from "next";
import 'reflect-metadata';
import "./globals.css";
import dynamic from 'next/dynamic';

//import NavBar from './ui/navbar/NavBar';
//import Content from './ui/Content';

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const Telo = dynamic(() => import('./Telo'), {
	ssr: false
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Telo children={children} />
			</body>
		</html >
	);
}
