import type { Metadata } from "next";
import 'reflect-metadata';
import "./globals.css";
import NavBar from './ui/navbar/NavBar';
import Content from './ui/Content';

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<main className="overflow-hidden relative flex max-w-4xl min-h-screen flex-col items-center my-o mx-auto">
					<NavBar />
					<Content children={children} />
				</main>
			</body >
		</html >
	);
}
